Catch missing filename error. Disadvantage: cannot have a filename that starts with a hyphen

diff --git a/common b/common
--- a/common
+++ b/common
@@ -27,6 +27,7 @@ normalpath () {
     local s="$1"
     [[ ${#s} -lt 800 ]] || fatal "Option path too long"
     [[ $s =~ ^[[:print:]]*$ ]] || fatal "Non-printables in path"
+    [[ $s =~ ^-*$ ]] || fatal "Parameter error. Check for missing filename"
     dir=$(dirname "$1")
     bas=$(basename "$1")
     echo $(cd $dir && pwd)/$bas
